name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for changelog

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build project for distribution
        run: hatch build -t wheel -t sdist -t binary

      - name: Generate changelog with git-cliff
        uses: tj-actions/git-cliff@v1
        with:
          args: --latest --strip all
          template-config: .github/cliff-template.toml
          output: "CHANGELOG.md"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**"
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "CHANGELOG.md"
          draft: false
          prerelease: false

      - name: Publish to PyPI
        env:
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: hatch publish
