name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Install scoop on Windows
        uses: MinoruSekine/setup-scoop@v4

      - name: Install required tools on Windows
        run: scoop install opus-tools ffmpeg flac

      - name: Run tests
        run: hatch test -all -vv

